### ISSUE TITLE
05/04/24 - Single namespace installation

### ISSUE THREAD

**Issue by Zvezdoreel** [kubernetes-sigs/container-object-storage-interface-controller#120]
# Enhancement

**Is your feature request related to a problem?/Why is this needed**
I want to deploy multiple instances of this controller in different namespaces

**Describe the solution you'd like in detail**
per namespace installation, Id like the controller to watch resources in the namespace it installed in

**Describe alternatives you've considered**
maybe a list of allowed namespaces

**Comment by niranjandarshann** [comment]
@Zvezdoreel  Thank you For your contribution.  I find this as  required one too as Implementing  per-namespace installation so that each controller instance is limited to watching resources in its own namespace. This simplifies management and ensures better isolation between different namespaces.

It is useful for better isolation between different namespaces.

**Comment by niranjandarshann** [comment]
@Zvezdoreel  I was looking for the alternative way to achieve it and here what i understood is that we can achieve it by:
Deploying  a controller in each namespace, configuring each instance to watch only its namespace using the WATCH_NAMESPACE environment variable. This ensures isolation and simple management. Alternatively, deploy a cluster-wide controller with namespace filtering logic and use Kubernetes RBAC to restrict its permissions. This approach balances isolation with resource efficiency.
