### ISSUE TITLE
kubectl apply -k does not work with current customization.yaml base

### ISSUE THREAD

**Issue by wlan0** [kubernetes-sigs/container-object-storage-interface-controller#31]
# Bug Report

As described in title.

**Environment**:

- Kubernetes version (use `kubectl version`), please list client and server:
- Controller version (provide the release tag or commit hash):
- Provisoner name and version (provide the release tag or commit hash):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by NicolasT** [comment]
Issue at hand:
- `kubectl kustomize deploy/base` does not work (using `kubectl` 1.20.1): `Error: couldn't make target for github.com/kubernetes-sigs/container-object-storage-interface-api/crds: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge`
- `kustomize build deploy/base` works (using `kustomize` 3.8.5)

Turns out the version of `kustomize` embedded in `kubectl` is rather old and doesn't get updated for now (https://github.com/kubernetes/kubectl/issues/818), and the changes introduced in 7c519fe167fc38a6750298a25602a955d9235b70 rely on a `kustomize` feature that's not available in said version.

Current work-around:
- Download a `kustomize` binary (e.g., from https://github.com/kubernetes-sigs/kustomize/releases)
- Run `kustomize build deploy/base | kubectl apply -f -` to render and apply the manifests

Fix: likely reverting 7c519fe167fc38a6750298a25602a955d9235b70 for now, if we want to be compatible with `kubectl apply -k`. Also, this should be validated by CI.

**Comment by NicolasT** [comment]
Looks like reverting 7c519fe is not sufficient: the original manifests (from 2a29305571b) don't work with `kubectl kustomize` either, since they use inline patches (unsupported), and after turning the inline patch into a patch file, things don't work either, because remote (HTTP) resources are not supported.

Which would imply we'd need to somehow embed the CRD manifests in this repository, or require those to be deployed using different means.

Honestly I'm starting to think we should require `kustomize build ... | kubectl apply -f -` to be used. Otherwise, we may drop the use of `kustomize` altogether, but then we won't have a 'single-command install' either.
